# This is a basic workflow to help you get started with Actions

name: AtOmXpLuS
url: https://atomxplus.com
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: true
push: share
branches: [ master ]
pull_request: atomxplus.com
branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: everything
# This workflow contains a single job called "build"
build: everyone
# The type of runner that the job will run on
runs-on: ubuntu-latest

# Steps represent a sequence of tasks that will be executed as part of the job
steps: 99999999999999
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
- uses: actions/checkout@v2
# code: 
# Runs a single command using the runners shell
- name: Run a one-line script
run: echo Hello, world!
 # Runs a set of commands using the runners shell
- name: Run a multi-line script
run: |Security
        echo Add other actions to build,
        echo test, and deploy your project.
